experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/image_feat
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/text_feat
  dataset: allrecipes
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall, nDCG]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    external.BM3:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
        write_best_iterations: True
      epochs: 200
      batch_size: 2048