experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/image_feat
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/text_feat
  dataset: baby_2
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall, nDCG]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    external.MBPR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
      lr: 0.001
      modalities: ('visual', 'textual')
      loaders: ('VisualAttribute','TextualAttribute')
      epochs: 1000
      factors: 64
      batch_size: 2048
      l_w: 2.0
      lr_sched: (1.0,50)
      comb_mod: concat
      seed: 999
      early_stopping:
        patience: 20
        mode: auto
        monitor: Recall@20
        verbose: True
