experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/image_feat
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/text_feat
  dataset: sports
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall, nDCG]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    external.VBPR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
      lr: 0.0005
      modalities: ('visual', 'textual')
      epochs: 200
      factors: 64
      batch_size: 1024
      l_w: 1e-5
      comb_mod: concat
      seed: 123
      early_stopping:
        patience: 10
        mode: auto
        monitor: Recall@20
        verbose: True